volumes:
  modules_data:

name: nodejs_devcontainer # rename this to your project name
services:
  app:
    build: .
    volumes:
      - ..:/usr/src
      - modules_data:/usr/src/node_modules
    command: tail -f /dev/null
    working_dir: /usr/src